### ISSUE TITLE
Steg 5  - Kinsta

### ISSUE THREAD

**Issue by lissmeister** [triggerfishab/lisa-cli#3]
```
🎉 StackPath site created for production environment
TypeError: Cannot read properties of undefined (reading 'pullzone')
    at setupStackpath (file:///Users/liss/.config/yarn/global/node_modules/lisa-cli/tasks/services/stackpath.js:36:59)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async setupServices (file:///Users/liss/.config/yarn/global/node_modules/lisa-cli/tasks/services/services.js:28:3)
    at async Command.init (file:///Users/liss/.config/yarn/global/node_modules/lisa-cli/commands/init.js:23:3)
```

**Comment by joiglifberg** [comment]
Please upgrade to version 2.2.1 and re-run the command.

**Comment by moelleer** [comment]
Stackpath is not used anymore https://github.com/triggerfishab/lisa-cli/releases/tag/v2.4.0
